name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy-backend:
    runs-on: self-hosted

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Build the backend application
    - name: Build Backend Application
      run: |
        cd ~/actions-runner/_work/Creditsea-assignment/Creditsea-assignment/backend
        npm install
        npm run build

    # Restart the application using PM2
    - name: Restart Server with PM2
      run: |
        cd ~/actions-runner/_work/Creditsea-assignment/Creditsea-assignment/backend
        pm2 restart server
