name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy-backend:
    runs-on: self-hosted

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Build the backend application
    - name: Build Backend Application
      run: |
        cd backend
        npm install
        npm run build

    # Deploy and Restart with PM2
    - name: Deploy with PM2
      run: |
        cd backend

        # Restart the application with PM2
        pm2 reload all --update-env
